#index:
#    path: /
#    controller: App\Controller\DefaultController::index

beers_simple:
    path: /simple/query={food}
    controller: App\Controller\BeersController::simple
    methods: GET

beers_full:
    path: /full/query={food}
    controller: App\Controller\BeersController::full
    methods: GET